export const TYPES = {
	BILLING: 'BILLING',
	OUTAGE: 'OUTAGE',
	SUPPORT: 'SUPPORT',
	STORAGE: 'STORAGE',
	BUG: 'BUG',
	FEATURE: 'FEATURE',
	IMPROVEMENT: 'IMPROVEMENT',
	OTHER: 'OTHER',
};

export const SEVERITIES = {
	LOW: 'LOW',
	MEDIUM: 'MEDIUM',
	HIGH: 'HIGH',
	URGENT: 'URGENT',
};

export const MENU = {
	OVERVIEW: 'OVERVIEW',
	MANAGE: 'MANAGE STORAGE',
	ADD_STORAGE: 'ADD STORAGE',
	REMOVE_STORAGE: 'DELETE STORAGE',
};

export const FIELDS = {
	LOCATION: 'Primary Location',
	SECONDARY_LOCATION: 'Secondary Location',
	ACCESSIBILITY: 'Accessibility',
	NAME: 'Storage Name',
	TYPE: 'Type',
	REDUNDANT: 'Redundant ?',
	WHITELIST: 'Whitelist Subnet',
};

export const STORAGE_MESSAGE = {
	START: 'Need to setup another share?  ',
	CONTENT: "If you give us the details, we'll get another share setup for you ASAP!",
};

export const PASSWORD_UPDATE_STATUS = {
	SUCCESS: 'SUCCESS',
	ERROR: 'ERROR',
	NOT_STARTED: 'NOT_STARTED',
};

export const SAMPLE_SHARE = {
	NAME: 'SHARE NAME',
	LOCATION: 'ATLANTA',
	TYPE: 'FILE ACCESS',
	VLAN: '1111',
	ACCESSIBILITY: 'PUBLIC',
	ASSIGNED_IP: 'ASSIGNED IP',
	WHITELIST: 'WHITELIST SUBNET',
};

export const LAYOUT_GRID_SHARE_DETAILS = {
	xs: [
		{ i: 'share-name-label', x: 1, y: 1, w: 3, h: 1.5, static: true },
		{ i: 'share-config', x: 1, y: 3, w: 5, h: 12, static: true },
		{ i: 'share-path-label', x: 1, y: 12, w: 2, h: 1.5, static: true },
		{ i: 'network-config', x: 1, y: 19, w: 5, h: 8, static: true },
		{ i: 'trending-label', x: 6, y: 1, w: 2, h: 1.5, static: true },
		{ i: 'access', x: 5, y: 1, w: 1, h: 1.5, static: true },
		{ i: 'horizontal-bar', x: 0, y: 30, w: 10, h: 1, static: true },
		{ i: 'trend-graph-label', x: 1, y: 5, w: 2, h: 1.5, static: true },
		{ i: 'trend-graph', x: 1, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'network-graph-label', x: 5.5, y: 5, w: 3, h: 1.5, static: true },
		{ i: 'network-graph', x: 5.5, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'share-graph-label', x: 5.5, y: 18, w: 3, h: 1.5, static: true },
		{ i: 'share-graph', x: 5.5, y: 20, w: 4.5, h: 9, static: true },
		{ i: 'shares-label', x: 1, y: 32, w: 4, h: 1.5, static: true },
		{ i: 'shares', x: 1, y: 34, w: 7, h: 9, static: true },
		{ i: 'add-storage', x: 8.5, y: 34, w: 3, h: 9, static: true },
	],
	sm: [
		{ i: 'share-name-label', x: 1, y: 1, w: 3, h: 1.5, static: true },
		{ i: 'share-config', x: 1, y: 3, w: 5, h: 12, static: true },
		{ i: 'share-path-label', x: 1, y: 12, w: 2, h: 1.5, static: true },
		{ i: 'network-config', x: 1, y: 19, w: 5, h: 8, static: true },
		{ i: 'trending-label', x: 6, y: 1, w: 2, h: 1.5, static: true },
		{ i: 'access', x: 5, y: 1, w: 1, h: 1.5, static: true },
		{ i: 'horizontal-bar', x: 0, y: 30, w: 10, h: 1, static: true },
		{ i: 'trend-graph-label', x: 1, y: 5, w: 2, h: 1.5, static: true },
		{ i: 'trend-graph', x: 1, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'network-graph-label', x: 5.5, y: 5, w: 3, h: 1.5, static: true },
		{ i: 'network-graph', x: 5.5, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'share-graph-label', x: 5.5, y: 18, w: 3, h: 1.5, static: true },
		{ i: 'share-graph', x: 5.5, y: 20, w: 4.5, h: 9, static: true },
		{ i: 'shares-label', x: 1, y: 32, w: 4, h: 1.5, static: true },
		{ i: 'shares', x: 1, y: 34, w: 7, h: 9, static: true },
		{ i: 'add-storage', x: 8.5, y: 34, w: 3, h: 9, static: true },
	],
	md: [
		{ i: 'share-name-label', x: 1, y: 1, w: 3, h: 1.5, static: true },
		{ i: 'share-config', x: 1, y: 3, w: 5, h: 12, static: true },
		{ i: 'share-path-label', x: 1, y: 12, w: 2, h: 1.5, static: true },
		{ i: 'network-config', x: 1, y: 19, w: 5, h: 8, static: true },
		{ i: 'trending-label', x: 6, y: 1, w: 2, h: 1.5, static: true },
		{ i: 'access', x: 5, y: 1, w: 1, h: 1.5, static: true },
		{ i: 'horizontal-bar', x: 0, y: 30, w: 10, h: 1, static: true },
		{ i: 'trend-graph-label', x: 1, y: 5, w: 2, h: 1.5, static: true },
		{ i: 'trend-graph', x: 1, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'network-graph-label', x: 5.5, y: 5, w: 3, h: 1.5, static: true },
		{ i: 'network-graph', x: 5.5, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'share-graph-label', x: 5.5, y: 18, w: 3, h: 1.5, static: true },
		{ i: 'share-graph', x: 5.5, y: 20, w: 4.5, h: 9, static: true },
		{ i: 'shares-label', x: 1, y: 32, w: 4, h: 1.5, static: true },
		{ i: 'shares', x: 1, y: 34, w: 7, h: 9, static: true },
		{ i: 'add-storage', x: 8.5, y: 34, w: 3, h: 9, static: true },
	],
	lg: [
		{ i: 'share-name-label', x: 1, y: 1, w: 3, h: 1.5, static: true },
		{ i: 'share-config', x: 1, y: 3, w: 5, h: 12, static: true },
		{ i: 'share-path-label', x: 1, y: 12, w: 2, h: 1.5, static: true },
		{ i: 'network-config', x: 1, y: 19, w: 5, h: 8, static: true },
		{ i: 'trending-label', x: 6, y: 1, w: 2, h: 1.5, static: true },
		{ i: 'access', x: 5, y: 1, w: 1, h: 1.5, static: true },
		{ i: 'horizontal-bar', x: 0, y: 30, w: 10, h: 1, static: true },
		{ i: 'trend-graph-label', x: 1, y: 5, w: 2, h: 1.5, static: true },
		{ i: 'trend-graph', x: 1, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'network-graph-label', x: 5.5, y: 5, w: 3, h: 1.5, static: true },
		{ i: 'network-graph', x: 5.5, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'share-graph-label', x: 5.5, y: 18, w: 3, h: 1.5, static: true },
		{ i: 'share-graph', x: 5.5, y: 20, w: 4.5, h: 9, static: true },
		{ i: 'shares-label', x: 1, y: 32, w: 4, h: 1.5, static: true },
		{ i: 'shares', x: 1, y: 34, w: 7, h: 9, static: true },
		{ i: 'add-storage', x: 8.5, y: 34, w: 3, h: 9, static: true },
	],
};

export const LAYOUT_GRID_MANAGE_STORAGE = {
	xs: [
		{ i: 'video', x: 1.5, y: 2, w: 9, h: 24, static: true },
		{ i: 'horizontal-bar', x: 0, y: 30, w: 10, h: 1, static: true },
		{ i: 'trend-graph-label', x: 1, y: 5, w: 2, h: 1.5, static: true },
		{ i: 'trend-graph', x: 1, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'network-graph-label', x: 5.5, y: 5, w: 3, h: 1.5, static: true },
		{ i: 'network-graph', x: 5.5, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'share-graph-label', x: 5.5, y: 20, w: 3, h: 1.5, static: true },
		{ i: 'share-graph', x: 5.5, y: 22, w: 4.5, h: 9, static: true },
		{ i: 'shares-label', x: 1, y: 32, w: 4, h: 1.5, static: true },
		{ i: 'shares', x: 1, y: 34, w: 7, h: 9, static: true },
		{ i: 'add-storage', x: 8.5, y: 34, w: 3, h: 9, static: true },
	],
	sm: [
		{ i: 'video', x: 1.5, y: 2, w: 9, h: 24, static: true },
		{ i: 'horizontal-bar', x: 0, y: 30, w: 10, h: 1, static: true },
		{ i: 'trend-graph-label', x: 1, y: 5, w: 2, h: 1.5, static: true },
		{ i: 'trend-graph', x: 1, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'network-graph-label', x: 5.5, y: 5, w: 3, h: 1.5, static: true },
		{ i: 'network-graph', x: 5.5, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'share-graph-label', x: 5.5, y: 20, w: 3, h: 1.5, static: true },
		{ i: 'share-graph', x: 5.5, y: 22, w: 4.5, h: 9, static: true },
		{ i: 'shares-label', x: 1, y: 32, w: 4, h: 1.5, static: true },
		{ i: 'shares', x: 1, y: 34, w: 7, h: 9, static: true },
		{ i: 'add-storage', x: 8.5, y: 34, w: 3, h: 9, static: true },
	],
	md: [
		{ i: 'video', x: 1.5, y: 2, w: 9, h: 24, static: true },
		{ i: 'horizontal-bar', x: 0, y: 30, w: 10, h: 1, static: true },
		{ i: 'trend-graph-label', x: 1, y: 5, w: 2, h: 1.5, static: true },
		{ i: 'trend-graph', x: 1, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'network-graph-label', x: 5.5, y: 5, w: 3, h: 1.5, static: true },
		{ i: 'network-graph', x: 5.5, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'share-graph-label', x: 5.5, y: 18, w: 3, h: 1.5, static: true },
		{ i: 'share-graph', x: 5.5, y: 20, w: 4.5, h: 9, static: true },
		{ i: 'shares-label', x: 1, y: 32, w: 4, h: 1.5, static: true },
		{ i: 'shares', x: 1, y: 34, w: 7, h: 9, static: true },
		{ i: 'add-storage', x: 8.5, y: 34, w: 3, h: 9, static: true },
	],
	lg: [
		{ i: 'video', x: 1.5, y: 2, w: 9, h: 24, static: true },
		{ i: 'horizontal-bar', x: 0, y: 30, w: 10, h: 1, static: true },
		{ i: 'trend-graph-label', x: 1, y: 5, w: 2, h: 1.5, static: true },
		{ i: 'trend-graph', x: 1, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'network-graph-label', x: 5.5, y: 5, w: 3, h: 1.5, static: true },
		{ i: 'network-graph', x: 5.5, y: 7, w: 4.5, h: 11, static: true },
		{ i: 'share-graph-label', x: 5.5, y: 20, w: 3, h: 1.5, static: true },
		{ i: 'share-graph', x: 5.5, y: 22, w: 4.5, h: 9, static: true },
		{ i: 'shares-label', x: 1, y: 32, w: 4, h: 1.5, static: true },
		{ i: 'shares', x: 1, y: 34, w: 7, h: 9, static: true },
		{ i: 'add-storage', x: 8.5, y: 34, w: 3, h: 9, static: true },
	],
};

export const LAYOUT_GRID = {
	xs: [
		{ i: 'add-storage-label', x: 1, y: 1, w: 3, h: 1.5, static: true },
		{ i: 'add-storage', x: 1, y: 3, w: 2, h: 7, static: true },
		{ i: 'storage-ticket-label', x: 4, y: 1, w: 3, h: 1, static: true },
		{ i: 'open-tickets', x: 4, y: 3, w: 2, h: 7, static: true },
		{ i: 'close-tickets', x: 6, y: 3, w: 2, h: 7, static: true },
		{ i: 'share-list-label', x: 7, y: 13, w: 2, h: 1, static: true },
		{ i: 'storage-graphs', x: 1, y: 13, w: 6, h: 34, static: true },
		{ i: 'share-list', x: 7, y: 15, w: 4, h: 18, static: true },
		{ i: 'horizontal-bar', x: 0, y: 11, w: 10, h: 1, static: true },
	],
	sm: [
		{ i: 'add-storage-label', x: 1, y: 1, w: 3, h: 1.5, static: true },
		{ i: 'add-storage', x: 1, y: 3, w: 2, h: 7, static: true },
		{ i: 'storage-ticket-label', x: 4, y: 1, w: 3, h: 1, static: true },
		{ i: 'open-tickets', x: 4, y: 3, w: 2, h: 7, static: true },
		{ i: 'close-tickets', x: 6, y: 3, w: 2, h: 7, static: true },
		{ i: 'share-list-label', x: 7, y: 13, w: 2, h: 1, static: true },
		{ i: 'storage-graphs', x: 1, y: 13, w: 6, h: 34, static: true },
		{ i: 'share-list', x: 7, y: 15, w: 4, h: 18, static: true },
		{ i: 'horizontal-bar', x: 0, y: 11, w: 10, h: 1, static: true },
	],
	md: [
		{ i: 'add-storage-label', x: 1, y: 1, w: 3, h: 1.5, static: true },
		{ i: 'add-storage', x: 1, y: 3, w: 2, h: 7, static: true },
		{ i: 'storage-ticket-label', x: 4, y: 1, w: 3, h: 1, static: true },
		{ i: 'open-tickets', x: 4, y: 3, w: 2, h: 7, static: true },
		{ i: 'close-tickets', x: 6, y: 3, w: 2, h: 7, static: true },
		{ i: 'share-list-label', x: 7, y: 13, w: 2, h: 1, static: true },
		{ i: 'storage-graphs', x: 1, y: 13, w: 6, h: 34, static: true },
		{ i: 'share-list', x: 7, y: 15, w: 4, h: 18, static: true },
		{ i: 'horizontal-bar', x: 0, y: 11, w: 10, h: 1, static: true },
	],
	lg: [
		{ i: 'add-storage-label', x: 1, y: 1, w: 3, h: 1.5, static: true },
		{ i: 'add-storage', x: 1, y: 3, w: 2, h: 7, static: true },
		{ i: 'storage-ticket-label', x: 4, y: 1, w: 3, h: 1, static: true },
		{ i: 'open-tickets', x: 4, y: 3, w: 2, h: 7, static: true },
		{ i: 'close-tickets', x: 6, y: 3, w: 2, h: 7, static: true },
		{ i: 'share-list-label', x: 7, y: 13, w: 2, h: 1, static: true },
		{ i: 'storage-graphs', x: 1, y: 13, w: 6, h: 34, static: true },
		{ i: 'share-list', x: 7, y: 15, w: 4, h: 18, static: true },
		{ i: 'object-storage', x: 1, y: 32, w: 6, h: 14, static: true },
		{ i: 'horizontal-bar', x: 0, y: 11, w: 10, h: 1, static: true },
	],
};
export const LAYOUT_GRID_STORAGE = {
	xs: [
		{ i: 'delete-storage-image', x: 4, y: 4, w: 4, h: 15, static: true },
		{ i: 'large-text', x: 3.5, y: 21, w: 5, h: 4, static: true },
		{ i: 'small-text', x: 3, y: 26, w: 6, h: 3, static: true },
		{ i: 'back-button', x: 4, y: 32, w: 2, h: 3, static: true },
		{ i: 'next-button', x: 6, y: 32, w: 2, h: 3, static: true },
		{ i: 'delete-input', x: 4, y: 29, w: 4, h: 4, static: true },
	],
	sm: [
		{ i: 'delete-storage-image', x: 4, y: 4, w: 4, h: 15, static: true },
		{ i: 'delete-input', x: 4, y: 29, w: 4, h: 4, static: true },
		{ i: 'large-text', x: 3.5, y: 21, w: 5, h: 4, static: true },
		{ i: 'small-text', x: 3, y: 26, w: 6, h: 3, static: true },
		{ i: 'back-button', x: 4, y: 32, w: 2, h: 3, static: true },
		{ i: 'next-button', x: 6, y: 32, w: 2, h: 3, static: true },
	],
	md: [
		{ i: 'delete-input', x: 4, y: 29, w: 4, h: 4, static: true },
		{ i: 'delete-storage-image', x: 4, y: 4, w: 4, h: 15, static: true },
		{ i: 'large-text', x: 3.5, y: 21, w: 5, h: 4, static: true },
		{ i: 'small-text', x: 3, y: 26, w: 6, h: 3, static: true },
		{ i: 'back-button', x: 3, y: 32, w: 3, h: 3, static: true },
		{ i: 'next-button', x: 6, y: 32, w: 3, h: 3, static: true },
	],
	lg: [
		{ i: 'delete-storage-image', x: 4, y: 4, w: 4, h: 15, static: true },
		{ i: 'large-text', x: 3.5, y: 21, w: 5, h: 4, static: true },
		{ i: 'small-text', x: 3, y: 26, w: 6, h: 3, static: true },
		{ i: 'back-button', x: 4, y: 32, w: 2, h: 3, static: true },
		{ i: 'next-button', x: 6, y: 32, w: 2, h: 3, static: true },
		{ i: 'delete-input', x: 4, y: 29, w: 4, h: 4, static: true },
	],
};

export const LOCATION_THEME = {
	COLOR: {
		ATL: '#df6a2e',
		CHA: '#8060a9',
		HSV: '#416ba9',
		BHM: '#a8ad00',
	},
};
